#
# Copyright 2013-2025 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: 'SonarQube PR Analysis'
description: 'A GitHub Action to perform SonarQube analysis on a PR with caching and metrics retrieval.'

inputs:
  sonar-project-key:
    description: 'SonarQube project key'
    required: true
  application-dir:
    description: 'Application directory'
    required: true
  docker-compose-file:
    description: 'Path to the Docker Compose file'
    required: true
  comment-token:
    description: 'GitHub token for commenting on the PR'
    required: true

runs:
  using: composite
  steps:
    # Make sure the sonar project folder exists.
    - env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: mkdir -p "./$SONAR_PROJECT_KEY"
      shell: bash

    # Cache the main branch project for future PR analysis
    - name: 'Cache project on main branch'
      if: github.ref == 'refs/heads/main'
      shell: bash
      env:
        APPLICATION_DIR: ${{ inputs.application-dir }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: |
        cd "$SONAR_PROJECT_KEY"
        cp -r "$APPLICATION_DIR"/. .
        rm -rf node_modules \
            package-lock.json \
            target/node \
            target/*.original \
            target/*.jar

    - name: 'Store cache (main branch)'
      if: github.ref == 'refs/heads/main'
      uses: actions/cache/save@v4
      with:
        path: ./${{ inputs.sonar-project-key }}
        key: application-${{ inputs.sonar-project-key }}-${{ github.sha }}

    # Restore the cache for PR analysis
    - name: 'Restore project cache for PR analysis'
      if: github.event_name == 'pull_request'
      id: restore_cache
      uses: actions/cache/restore@v4
      with:
        path: ./${{ inputs.sonar-project-key }}
        key: application-${{ inputs.sonar-project-key }}-${{ github.event.pull_request.base.sha }}
        restore-keys: |
          application-${{ inputs.sonar-project-key }}-

    # Start SonarQube server using Docker Compose
    - name: 'Start SonarQube server'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        DOCKER_COMPOSE_FILE: ${{ inputs.docker-compose-file }}
      run: |
        echo "::group::Starting sonarqube"
        docker compose -f "$DOCKER_COMPOSE_FILE" up --build -d --wait
        echo "::endgroup::"

    # Create SonarQube project
    - name: 'Setup SonarQube'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: |
        SONAR_HOST_URL=http://localhost:9000
        LOCAL_SONAR_LOGIN=admin
        LOCAL_SONAR_PASSWORD=admin

        SONAR_TOKEN=$(curl -s -u $LOCAL_SONAR_LOGIN:$LOCAL_SONAR_PASSWORD -X POST "$SONAR_HOST_URL/api/user_tokens/generate?login=$LOCAL_SONAR_LOGIN&name=token&type=USER_TOKEN" | jq -r '.token')

        curl -s -u $SONAR_TOKEN: -X POST "$SONAR_HOST_URL/api/projects/create?name=$SONAR_PROJECT_KEY&project=$SONAR_PROJECT_KEY"
        curl -s -u $SONAR_TOKEN: -X POST "$SONAR_HOST_URL/api/permissions/add_user?login=$LOCAL_SONAR_LOGIN&permission=scan"

        echo "SONAR_HOST_URL=$SONAR_HOST_URL" >> $GITHUB_ENV
        echo "SONAR_TOKEN=$SONAR_TOKEN" >> $GITHUB_ENV

    # Run SonarQube analysis on the main branch or add an empty scan
    - name: 'Run SonarQube analysis on main branch'
      if: github.event_name == 'pull_request' && steps.restore_cache.outputs.cache-matched-key
      shell: bash
      env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: >-
        cd "$SONAR_PROJECT_KEY" &&
        echo "::group::Scanning main branch application" &&
        ./mvnw --batch-mode initialize org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
        -Denforcer.skip=true
        -Dsonar.projectKey="$SONAR_PROJECT_KEY"
        -Dsonar.branch.name=main &&
        echo "::endgroup::"

    - name: Add an empty scan to sonar main branch
      if: github.event_name == 'pull_request' && !steps.restore_cache.outputs.cache-matched-key
      shell: bash
      env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: >-
        cd "$SONAR_PROJECT_KEY" &&
        echo "::group::Scanning empty commit" &&
        git init &&
        git commit -m "Initial commit" --allow-empty &&
        docker run --net=host -v ".:/usr/src" -e SONAR_HOST_URL -e SONAR_TOKEN --rm sonarsource/sonar-scanner-cli
        -Dsonar.projectKey="$SONAR_PROJECT_KEY"
        -Dsonar.branch.name=main &&
        echo "::endgroup::"

    # Prepare the repository for the PR changes
    - name: 'Clean repository for PR changes'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: |
        cd "$SONAR_PROJECT_KEY"
        find . -mindepth 1 -not -path "./.git*" -delete

    - name: 'Apply PR changes to the repository'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        APPLICATION_DIR: ${{ inputs.application-dir }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: |
        echo "::group::Creating changes commit"
        rm -rf "$APPLICATION_DIR/.git"
        cd "$SONAR_PROJECT_KEY"
        cp -r "$APPLICATION_DIR"/. .

        git checkout -b dev
        git add -A
        git commit -m "Apply changes from PR branch"
        echo "::endgroup::"

    # Run SonarQube analysis on the PR changes
    - name: 'Run SonarQube analysis on PR changes'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: >-
        cd "$SONAR_PROJECT_KEY" &&
        echo "::group::Scanning PR application changes" &&
        ./mvnw --batch-mode initialize org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
        -Dsonar.projectKey="$SONAR_PROJECT_KEY"
        -Dsonar.pullrequest.key="$PR_NUMBER"
        -Dsonar.pullrequest.branch=dev
        -Dsonar.pullrequest.base=main
        -Dsonar.scm.revision=$(git rev-parse HEAD) &&
        echo "::endgroup::"

    # Wait for SonarQube tasks to complete
    - name: 'Wait for SonarQube tasks to complete'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: |
        timeout 300s bash -c 'while :; do
          response=$(curl -s -u $SONAR_TOKEN: "$SONAR_HOST_URL/api/ce/component?component=$SONAR_PROJECT_KEY")
          queue_status=$(echo "$response" | jq -r ".queue[]?.status")
          current_status=$(echo "$response" | jq -r ".current.status")

          if [[ "$queue_status" == "" && "$current_status" != "IN_PROGRESS" ]]; then
            echo "All tasks completed or no tasks pending."
            break
          fi

          if [[ "$queue_status" == "PENDING" || "$queue_status" == "IN_PROGRESS" || "$current_status" == "IN_PROGRESS" ]]; then
            echo "Tasks are still in progress or pending. Waiting..."
            sleep 10
          else
            echo "All tasks completed."
            break
          fi
        done' || (echo "SonarQube tasks failed to complete in time" && exit 1)

    # Retrieve SonarQube metrics for the PR
    - name: 'Retrieve SonarQube metrics'
      if: github.event_name == 'pull_request'
      id: sonar_metrics
      shell: bash
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      run: |
        SONAR_RESPONSE=$(curl -s -u $SONAR_TOKEN: \
          "$SONAR_HOST_URL/api/measures/component?component=$SONAR_PROJECT_KEY&pullRequest=$PR_NUMBER&metricKeys=new_bugs,new_vulnerabilities,new_code_smells,new_coverage,new_duplicated_lines_density,new_violations")
        echo ":::group::PR SonarQube Analysis"
        echo "$SONAR_RESPONSE"
        echo "::endgroup::"

        SONAR_RESPONSE_MAIN=$(curl -s -u $SONAR_TOKEN: \
          "$SONAR_HOST_URL/api/measures/component?component=$SONAR_PROJECT_KEY&metricKeys=violations")
        echo ":::group::SonarQube Analysis"
        echo "$SONAR_RESPONSE_MAIN"
        echo "::endgroup::"

        export_measure() {
          METRIC_NAME=$1
          ENV_VAR_NAME=$2
          METRIC_VALUE=$(echo "$SONAR_RESPONSE" | jq -r ".component.measures[] | select(.metric == \"$METRIC_NAME\") | .period.value")
          if [ -z "$METRIC_VALUE" ] || [ "$METRIC_VALUE" == "null" ]; then
            METRIC_VALUE="N/A"
          fi
          echo "$ENV_VAR_NAME=$METRIC_VALUE" >> $GITHUB_ENV
          export $ENV_VAR_NAME=$METRIC_VALUE
        }

        print_main_metric() {
          METRIC_NAME=$1
          METRIC_VALUE=$(echo "$SONAR_RESPONSE_MAIN" | jq -r ".component.measures[] | select(.metric == \"$METRIC_NAME\") | .value")
          if [ -z "$METRIC_VALUE" ] || [ "$METRIC_VALUE" == "null" ]; then
            METRIC_VALUE="N/A"
          fi
          echo "${METRIC_VALUE}"
        }

        export_measure "new_vulnerabilities" "NEW_VUL"
        export_measure "new_code_smells" "NEW_CSM"
        export_measure "new_bugs" "NEW_BUG"
        export_measure "new_violations" "NEW_VIOLATIONS"
        export_measure "violations" "VIOLATIONS"
        export_measure "new_coverage" "NEW_COV"
        export_measure "new_duplicated_lines_density" "NEW_DUP"

        {
          echo "## :bar_chart: SonarQube Analysis for $SONAR_PROJECT_KEY"
          echo ""
          echo "| Metric                      | Value       |"
          echo "|-----------------------------|-------------|"
          echo "| **Total Violations**        | $(print_main_metric "violations") |"
          echo "| **New Vulnerabilities**     | ${NEW_VUL} |"
          echo "| **New Bugs**                | ${NEW_BUG} |"
          echo "| **New Code smells**         | ${NEW_CSM} |"
          echo "| **Coverage on New Code**    | ${NEW_COV}% |"
          echo "| **Duplication on New Code** | ${NEW_DUP}% |"

          if [[ "${NEW_VIOLATIONS}" != "N/A" && "${NEW_VIOLATIONS}" != "0" ]]; then
            echo ""
            echo "<details><summary>Unresolved New Issues (click to expand)</summary>"
            echo ""
            ISSUES=$(curl -s -u $SONAR_TOKEN: \
              "$SONAR_HOST_URL/api/issues/search?componentKeys=$SONAR_PROJECT_KEY&resolved=false&pullRequest=$PR_NUMBER" | \
              jq -r '.issues[] | "File: \(.component) Line: \(.line)\n  [\(.rule)] \(.message)\n"')
            echo "$ISSUES"
            echo "</details>"
          fi
        } > sonar_result.md

        {
          echo 'COMMENT_BODY<<EOF'
          cat sonar_result.md
          echo 'EOF'
        } >> "$GITHUB_ENV"

        cat sonar_result.md >> $GITHUB_STEP_SUMMARY
        cat sonar_result.md

    # Find previous SonarQube analysis comment
    - name: 'Find existing PR comment with SonarQube results'
      if: github.event_name == 'pull_request' && inputs.comment-token && steps.sonar_metrics.outcome == 'success'
      id: find_comment
      uses: peter-evans/find-comment@v4
      env:
        SONAR_PROJECT_KEY: ${{ inputs.sonar-project-key }}
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: '## :bar_chart: SonarQube Analysis for ${{ env.SONAR_PROJECT_KEY }}'
        token: ${{ inputs.comment-token }}

    # Create or update PR comment with SonarQube results
    - name: 'Post SonarQube results as PR comment'
      if: github.event_name == 'pull_request' && inputs.comment-token && steps.sonar_metrics.outcome == 'success'
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ env.COMMENT_BODY }}
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        edit-mode: replace
        token: ${{ inputs.comment-token }}

    # Fail the action if there are unresolved issues
    - name: 'Fail PR if unresolved issues are found'
      if: >-
        github.event_name == 'pull_request' &&
        steps.sonar_metrics.outcome == 'success' &&
        env.NEW_VIOLATIONS != 'N/A' && env.NEW_VIOLATIONS != 0 &&
        !contains(github.event.pull_request.labels.*.name, 'pr: disable-sonar')
      shell: bash
      run: |
        echo "SonarQube PR Analysis failed due to unresolved issues."
        exit 1

    # Stop the SonarQube server
    - name: 'Stop SonarQube server'
      if: github.event_name == 'pull_request'
      shell: bash
      env:
        DOCKER_COMPOSE_FILE: ${{ inputs.docker-compose-file }}
      run: |
        echo "::group::Stopping SonarQube"
        docker compose -f "$DOCKER_COMPOSE_FILE" down
        echo "::endgroup::"
